### ISSUE TITLE
What path we have to provide of asset in library so that after compilation it finds the asset in dist folder?

### ISSUE THREAD

**Issue by mehulparmariitr** [linnenschmidt/build-ng-packagr#10]
Hey,
What path we have to provide of our assets in the library code so that after compilation it finds the assets in dist folder?
For eg - 
In my library code, the asset folder is at this location.
![image](https://user-images.githubusercontent.com/11155969/85321323-2683c580-b4e2-11ea-9495-e68bcb75adae.png)

And the path of the assets I have provided in the library is with this respect to the asset folder in the library code(inside the src folder). 

After compilation of dist, the assets folder will be in the root folder of the library.
![image](https://user-images.githubusercontent.com/11155969/85321726-c5102680-b4e2-11ea-89dc-ac368788b5ea.png)

So what path should I provide in my original library source code of assets?

**Comment by nakedfool** [comment]
Any news on this?
