### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by dphochman** [linnenschmidt/build-ng-packagr#14]
We depend on build-ng-packagr and appreciate what you have done.
Please upgrade it for Angular 10.
Our library project is upgraded to Angular 10, and we see these dependency issues related to build-ng-packagr:
```
npm WARN @linnenschmidt/build-ng-packagr@9.0.0 requires a peer of ng-packagr@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-ng-packagr@0.900.1 requires a peer of ng-packagr@^9.0.0-rc.7 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/plugin-commonjs@15.0.0 requires a peer of rollup@^2.22.0 but none is installed. You must install peer dependencies yourself.
```

Thank you!

**Comment by dphochman** [comment]
in Angular 10 we run `ngcc` after a build, which produces '*.__ivy_ngcc_bak' files. 
How can we configure build-ng-packagr to ignore these files is the "glob" pattern under assets?

I tried `"glob": ["!**/*.__ivy_ngcc_bak", "**/*"],`, but see this error when building:
```
Schema validation failed with the following errors:
  Data path ".assets[0].glob" should be string.
  Data path ".assets[0]" should be string.
  Data path ".assets[0]" should match exactly one schema in oneOf.
```

**Comment by JTHOUMEL** [comment]
@dphochman : did you found a solution to that issue at the end ?
