### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by meraj-ahmed** [linnenschmidt/build-ng-packagr#31]
I upgraded to Angular 13, and it appears that this package no longer works. I think this has been a great contribution that solves a very important issue for building Angular libraries. Is there any plan to continue to support newer versions of Angular?

**Comment by iursevla** [comment]
For someone that is facing this problem what I did was :

I used @mdudek changes (did a fork from his pull request) added some minor updates (mostly versions of packages) and now I have it working for Angular 13 on my company's library

Here's the npm package: https://www.npmjs.com/package/@iursevla/build-ng-packagr

The Github page is: https://github.com/iursevla/build-ng-packagr

If someone is able to test it, let me know if it worked.

You should only need to install (`npm i @iursevla/build-ng-packagr`) and then change the builder:
`          "builder": "@linnenschmidt/build-ng-packagr:build",` to `"builder": "@iursevla/build-ng-packagr:build",`

---

The best solution would be to update this package instead, but until @linnenschmidt merges [PR/30](https://github.com/linnenschmidt/build-ng-packagr/pull/30) you may be able to use my package and do just one change in your code to get everything to work as before
