### ISSUE TITLE
Angular 9 

### ISSUE THREAD

**Issue by Veoth** [linnenschmidt/build-ng-packagr#5]
Hey, first, thanks for this lib !

As you may know Angular 9 is about to be released really soon (RC-10 while speaking). 
What comes with this version is typescript 3.7 and it would be really nice to be able to update as soon as possible !
Last time I tried there were issues with some imported module from ng-packagr inside assets.ts

It would be awesome if you could give it a look ! Thanks

**Comment by mdudek** [comment]
Just tried with angular RC11 with following error:

Cannot find module 'ng-packagr/lib/ng-v5/discover-packages'

"ng-packagr": "^9.0.0-rc.7"

**Comment by linnenschmidt** [comment]
Hi there,
thanks for using the lib.
Did you tried the @next version?
https://www.npmjs.com/package/@linnenschmidt/build-ng-packagr/v/9.0.0-next.0

Which version did you use?

**Comment by mdudek** [comment]
Yes, i have used 9.0.0-next.0. It seems that ng-packagr@9.0.0-rc.7 changed package folder structure.

The reference 'ng-packagr/lib/ng-v5/discover-packages' should be changed to 'ng-packagr/lib/ng-package/discover-packages'.

**Comment by amarchese86** [comment]
Hello there,
just to add the same need here.
Your lib has been really useful, would really appreciate if you can update it for the latest Angular release.

Thank you!

**Comment by linnenschmidt** [comment]
Hi,
i have published a new @linnenschmidt/build-ng-packagr@next version.

https://www.npmjs.com/package/@linnenschmidt/build-ng-packagr/v/9.0.0-rc.0

Hopefully it works

**Comment by mdudek** [comment]
It's working right now, thanks a lot @linnenschmidt  ;-)

**Comment by linnenschmidt** [comment]
Have released the final version for Angular 9
